[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

monitor_speed = 115200

board_build.filesystem = littlefs

lib_deps =
    esphome/ESPAsyncWebServer-esphome
    esphome/AsyncTCP-esphome

lib_ignore = LittleFS_esp32
